"""Built-in starter catalog: copied into a device's cookbook on its first request.

Ratings, favorites and times_cooked always start empty — only the recipe
content itself is pre-filled.
"""

SEED_RECIPES = [
    # ---------------- Breakfast ----------------
    {
        "name": "Fluffy Pancakes",
        "category": "Breakfast",
        "cook_time_minutes": 20,
        "servings": 4,
        "difficulty": "Easy",
        "image": "seed_01.png",
        "ingredients": [
            ("Flour", "200 g"),
            ("Milk", "300 ml"),
            ("Egg", "2"),
            ("Sugar", "2 tbsp"),
            ("Baking powder", "2 tsp"),
            ("Butter", "30 g"),
            ("Salt", "1 pinch"),
        ],
        "steps": [
            "Whisk flour, sugar, baking powder and salt in a large bowl.",
            "In another bowl whisk milk, eggs and melted butter, then fold into the dry mix until just combined.",
            "Cook ladlefuls on a buttered pan over medium heat, 2 minutes per side until golden.",
            "Serve warm with honey or fruit.",
        ],
    },
    {
        "name": "Veggie Omelette",
        "category": "Breakfast",
        "cook_time_minutes": 15,
        "servings": 2,
        "difficulty": "Easy",
        "image": "seed_02.png",
        "ingredients": [
            ("Egg", "4"),
            ("Bell pepper", "1/2"),
            ("Onion", "1/2"),
            ("Mushrooms", "80 g"),
            ("Cheddar", "50 g"),
            ("Butter", "20 g"),
            ("Salt", "to taste"),
            ("Black pepper", "to taste"),
        ],
        "steps": [
            "Dice the pepper, onion and mushrooms and sauté in butter for 4 minutes.",
            "Whisk the eggs with salt and pepper and pour over the vegetables.",
            "Cook on low heat until almost set, sprinkle with grated cheddar.",
            "Fold in half and slide onto a plate.",
        ],
    },
    {
        "name": "Avocado Toast with Egg",
        "category": "Breakfast",
        "cook_time_minutes": 10,
        "servings": 2,
        "difficulty": "Easy",
        "image": "seed_03.png",
        "ingredients": [
            ("Bread", "2 slices"),
            ("Avocado", "1"),
            ("Egg", "2"),
            ("Lemon", "1/2"),
            ("Chili flakes", "1 pinch"),
            ("Olive oil", "1 tsp"),
            ("Salt", "to taste"),
        ],
        "steps": [
            "Toast the bread until crisp.",
            "Mash the avocado with lemon juice, olive oil and salt, spread on the toast.",
            "Fry or poach the eggs and place on top.",
            "Finish with chili flakes.",
        ],
    },
    {
        "name": "Overnight Oats",
        "category": "Breakfast",
        "cook_time_minutes": 5,
        "servings": 1,
        "difficulty": "Easy",
        "image": "seed_04.png",
        "ingredients": [
            ("Oats", "60 g"),
            ("Milk", "150 ml"),
            ("Yogurt", "3 tbsp"),
            ("Honey", "1 tbsp"),
            ("Banana", "1/2"),
            ("Blueberries", "50 g"),
            ("Cinnamon", "1/4 tsp"),
        ],
        "steps": [
            "Mix oats, milk, yogurt, honey and cinnamon in a jar.",
            "Refrigerate overnight (or at least 4 hours).",
            "Top with sliced banana and blueberries before serving.",
        ],
    },
    {
        "name": "French Toast",
        "category": "Breakfast",
        "cook_time_minutes": 20,
        "servings": 4,
        "difficulty": "Easy",
        "image": "seed_05.png",
        "ingredients": [
            ("Bread", "8 slices"),
            ("Egg", "3"),
            ("Milk", "150 ml"),
            ("Vanilla extract", "1 tsp"),
            ("Cinnamon", "1/2 tsp"),
            ("Butter", "40 g"),
            ("Maple syrup", "to serve"),
        ],
        "steps": [
            "Whisk eggs, milk, vanilla and cinnamon in a shallow dish.",
            "Dip each bread slice for 10 seconds per side.",
            "Fry in butter over medium heat until golden on both sides.",
            "Serve with maple syrup.",
        ],
    },
    {
        "name": "Shakshuka",
        "category": "Breakfast",
        "cook_time_minutes": 30,
        "servings": 4,
        "difficulty": "Medium",
        "image": "seed_06.png",
        "ingredients": [
            ("Egg", "4"),
            ("Tomato", "600 g"),
            ("Onion", "1"),
            ("Garlic", "3 cloves"),
            ("Bell pepper", "1"),
            ("Cumin", "1 tsp"),
            ("Paprika", "1 tsp"),
            ("Feta", "60 g"),
            ("Parsley", "small bunch"),
        ],
        "steps": [
            "Sauté sliced onion and pepper in olive oil until soft, add garlic, cumin and paprika.",
            "Add chopped tomatoes and simmer 10 minutes until thick.",
            "Make wells in the sauce and crack in the eggs.",
            "Cover and cook until the whites are set, top with feta and parsley.",
        ],
    },
    {
        "name": "Banana Smoothie Bowl",
        "category": "Breakfast",
        "cook_time_minutes": 10,
        "servings": 2,
        "difficulty": "Easy",
        "image": "seed_07.png",
        "ingredients": [
            ("Banana", "2"),
            ("Yogurt", "200 g"),
            ("Milk", "50 ml"),
            ("Honey", "1 tbsp"),
            ("Oats", "3 tbsp"),
            ("Strawberries", "100 g"),
            ("Almonds", "20 g"),
        ],
        "steps": [
            "Blend frozen bananas, yogurt, milk and honey until thick and creamy.",
            "Pour into bowls.",
            "Top with oats, sliced strawberries and chopped almonds.",
        ],
    },
    {
        "name": "Breakfast Burrito",
        "category": "Breakfast",
        "cook_time_minutes": 20,
        "servings": 2,
        "difficulty": "Medium",
        "image": "seed_08.png",
        "ingredients": [
            ("Tortilla", "2 large"),
            ("Egg", "4"),
            ("Bacon", "4 strips"),
            ("Cheddar", "60 g"),
            ("Avocado", "1"),
            ("Sour cream", "2 tbsp"),
            ("Tomato", "1"),
        ],
        "steps": [
            "Fry the bacon until crisp, drain and chop.",
            "Soft-scramble the eggs in the same pan.",
            "Warm the tortillas and layer eggs, bacon, cheddar, diced tomato and avocado.",
            "Add sour cream, fold in the sides and roll tightly.",
        ],
    },
    # ---------------- Lunch ----------------
    {
        "name": "Chicken Caesar Salad",
        "category": "Lunch",
        "cook_time_minutes": 25,
        "servings": 2,
        "difficulty": "Easy",
        "image": "seed_09.png",
        "ingredients": [
            ("Chicken breast", "1 large"),
            ("Romaine lettuce", "1 head"),
            ("Parmesan", "40 g"),
            ("Bread", "2 slices"),
            ("Garlic", "1 clove"),
            ("Olive oil", "3 tbsp"),
            ("Lemon", "1/2"),
            ("Mayonnaise", "2 tbsp"),
        ],
        "steps": [
            "Cube the bread, toss with olive oil and toast into croutons.",
            "Season and pan-fry the chicken 5–6 minutes per side, then slice.",
            "Whisk mayonnaise, lemon juice, grated garlic and half the parmesan into a dressing.",
            "Toss lettuce with the dressing, top with chicken, croutons and parmesan shavings.",
        ],
    },
    {
        "name": "Creamy Tomato Soup",
        "category": "Lunch",
        "cook_time_minutes": 35,
        "servings": 4,
        "difficulty": "Easy",
        "image": "seed_10.png",
        "ingredients": [
            ("Tomato", "1 kg"),
            ("Onion", "1"),
            ("Garlic", "2 cloves"),
            ("Cream", "100 ml"),
            ("Basil", "small bunch"),
            ("Olive oil", "2 tbsp"),
            ("Salt", "to taste"),
        ],
        "steps": [
            "Sauté chopped onion and garlic in olive oil until translucent.",
            "Add chopped tomatoes and simmer 20 minutes.",
            "Blend until smooth, stir in the cream and season.",
            "Serve with torn basil leaves.",
        ],
    },
    {
        "name": "Grilled Cheese Sandwich",
        "category": "Lunch",
        "cook_time_minutes": 10,
        "servings": 2,
        "difficulty": "Easy",
        "image": "seed_11.png",
        "ingredients": [
            ("Bread", "4 slices"),
            ("Cheddar", "80 g"),
            ("Mozzarella", "60 g"),
            ("Butter", "30 g"),
        ],
        "steps": [
            "Butter the outside of each bread slice.",
            "Fill with sliced cheddar and mozzarella.",
            "Fry over medium-low heat 3 minutes per side until deep golden and melted inside.",
        ],
    },
    {
        "name": "Chicken Wrap",
        "category": "Lunch",
        "cook_time_minutes": 20,
        "servings": 2,
        "difficulty": "Easy",
        "image": "seed_12.png",
        "ingredients": [
            ("Tortilla", "2 large"),
            ("Chicken breast", "1"),
            ("Lettuce", "4 leaves"),
            ("Tomato", "1"),
            ("Cucumber", "1/2"),
            ("Yogurt", "3 tbsp"),
            ("Garlic", "1 clove"),
        ],
        "steps": [
            "Season and grill the chicken, then slice into strips.",
            "Mix yogurt with grated garlic for the sauce.",
            "Layer lettuce, chicken, tomato and cucumber on the tortillas, drizzle with sauce.",
            "Roll tightly and cut in half.",
        ],
    },
    {
        "name": "Greek Salad",
        "category": "Lunch",
        "cook_time_minutes": 15,
        "servings": 4,
        "difficulty": "Easy",
        "image": "seed_13.png",
        "ingredients": [
            ("Cucumber", "1"),
            ("Tomato", "3"),
            ("Feta", "150 g"),
            ("Olives", "80 g"),
            ("Red onion", "1/2"),
            ("Olive oil", "3 tbsp"),
            ("Oregano", "1 tsp"),
        ],
        "steps": [
            "Cut cucumber and tomatoes into chunks, slice the onion thinly.",
            "Combine with olives in a bowl.",
            "Top with a slab of feta, drizzle with olive oil and sprinkle oregano.",
        ],
    },
    {
        "name": "Tuna Pasta Salad",
        "category": "Lunch",
        "cook_time_minutes": 25,
        "servings": 4,
        "difficulty": "Easy",
        "image": "seed_14.png",
        "ingredients": [
            ("Pasta", "250 g"),
            ("Tuna", "1 can"),
            ("Corn", "100 g"),
            ("Peas", "100 g"),
            ("Mayonnaise", "3 tbsp"),
            ("Lemon", "1/2"),
            ("Parsley", "small bunch"),
        ],
        "steps": [
            "Cook the pasta, adding the peas for the last 2 minutes; drain and cool.",
            "Flake the tuna and mix with corn, mayonnaise and lemon juice.",
            "Fold everything together and finish with chopped parsley.",
        ],
    },
    {
        "name": "Red Lentil Soup",
        "category": "Lunch",
        "cook_time_minutes": 45,
        "servings": 4,
        "difficulty": "Medium",
        "image": "seed_15.png",
        "ingredients": [
            ("Red lentils", "250 g"),
            ("Carrot", "1"),
            ("Celery", "1 stalk"),
            ("Onion", "1"),
            ("Garlic", "2 cloves"),
            ("Cumin", "1 tsp"),
            ("Olive oil", "2 tbsp"),
            ("Lemon", "1/2"),
        ],
        "steps": [
            "Sauté diced onion, carrot and celery in olive oil for 5 minutes.",
            "Add garlic and cumin, cook 1 minute more.",
            "Add rinsed lentils and 1 liter of water, simmer 25 minutes.",
            "Blend roughly, season and brighten with lemon juice.",
        ],
    },
    {
        "name": "Chicken Quesadilla",
        "category": "Lunch",
        "cook_time_minutes": 25,
        "servings": 2,
        "difficulty": "Medium",
        "image": "seed_16.png",
        "ingredients": [
            ("Tortilla", "2 large"),
            ("Chicken breast", "1"),
            ("Cheddar", "100 g"),
            ("Bell pepper", "1/2"),
            ("Onion", "1/2"),
            ("Sour cream", "to serve"),
        ],
        "steps": [
            "Cook sliced chicken with the pepper and onion until browned.",
            "Fill each tortilla with the mixture and grated cheddar, fold in half.",
            "Toast in a dry pan 2–3 minutes per side until crisp.",
            "Cut into wedges and serve with sour cream.",
        ],
    },
    # ---------------- Dinner ----------------
    {
        "name": "Spaghetti Bolognese",
        "category": "Dinner",
        "cook_time_minutes": 60,
        "servings": 4,
        "difficulty": "Medium",
        "image": "seed_17.png",
        "ingredients": [
            ("Spaghetti", "400 g"),
            ("Ground beef", "500 g"),
            ("Tomato", "800 g"),
            ("Onion", "1"),
            ("Garlic", "2 cloves"),
            ("Carrot", "1"),
            ("Parmesan", "to serve"),
            ("Oregano", "1 tsp"),
            ("Olive oil", "2 tbsp"),
        ],
        "steps": [
            "Sauté finely chopped onion, carrot and garlic in olive oil.",
            "Add the beef and brown it, breaking it up.",
            "Add chopped tomatoes and oregano, simmer 40 minutes on low.",
            "Cook the spaghetti, toss with the sauce and serve with parmesan.",
        ],
    },
    {
        "name": "Chicken Stir-Fry",
        "category": "Dinner",
        "cook_time_minutes": 25,
        "servings": 2,
        "difficulty": "Easy",
        "image": "seed_18.png",
        "ingredients": [
            ("Chicken breast", "2"),
            ("Soy sauce", "3 tbsp"),
            ("Ginger", "20 g"),
            ("Garlic", "2 cloves"),
            ("Broccoli", "1 head"),
            ("Bell pepper", "1"),
            ("Rice", "200 g"),
            ("Sesame oil", "1 tsp"),
        ],
        "steps": [
            "Cook the rice and keep warm.",
            "Stir-fry sliced chicken on high heat until golden, remove.",
            "Stir-fry broccoli and pepper 3 minutes, add ginger and garlic.",
            "Return chicken, add soy sauce and sesame oil, toss and serve over rice.",
        ],
    },
    {
        "name": "Baked Salmon with Vegetables",
        "category": "Dinner",
        "cook_time_minutes": 35,
        "servings": 2,
        "difficulty": "Easy",
        "image": "seed_19.png",
        "ingredients": [
            ("Salmon fillet", "2"),
            ("Lemon", "1"),
            ("Potato", "400 g"),
            ("Zucchini", "1"),
            ("Olive oil", "3 tbsp"),
            ("Thyme", "3 sprigs"),
            ("Garlic", "2 cloves"),
        ],
        "steps": [
            "Toss sliced potatoes with oil and roast at 200°C for 15 minutes.",
            "Add zucchini, garlic and the salmon fillets topped with lemon slices and thyme.",
            "Roast another 12–15 minutes until the salmon flakes easily.",
        ],
    },
    {
        "name": "Beef Tacos",
        "category": "Dinner",
        "cook_time_minutes": 30,
        "servings": 4,
        "difficulty": "Easy",
        "image": "seed_20.png",
        "ingredients": [
            ("Tortilla", "8 small"),
            ("Ground beef", "500 g"),
            ("Onion", "1"),
            ("Tomato", "2"),
            ("Lettuce", "4 leaves"),
            ("Cheddar", "80 g"),
            ("Lime", "1"),
            ("Cumin", "1 tsp"),
        ],
        "steps": [
            "Brown the beef with chopped onion and cumin, season well.",
            "Warm the tortillas in a dry pan.",
            "Fill with beef, diced tomato, shredded lettuce and cheddar.",
            "Squeeze lime over before serving.",
        ],
    },
    {
        "name": "Margherita Pizza",
        "category": "Dinner",
        "cook_time_minutes": 90,
        "servings": 4,
        "difficulty": "Hard",
        "image": "seed_21.png",
        "ingredients": [
            ("Flour", "500 g"),
            ("Yeast", "7 g"),
            ("Tomato", "400 g"),
            ("Mozzarella", "250 g"),
            ("Basil", "small bunch"),
            ("Olive oil", "3 tbsp"),
            ("Salt", "1 tsp"),
        ],
        "steps": [
            "Mix flour, yeast, salt and 320 ml warm water into a dough; knead 10 minutes.",
            "Let rise 1 hour until doubled.",
            "Stretch into two bases, spread crushed tomatoes, add torn mozzarella.",
            "Bake at max oven heat 8–10 minutes; finish with basil and olive oil.",
        ],
    },
    {
        "name": "Thai Green Curry",
        "category": "Dinner",
        "cook_time_minutes": 40,
        "servings": 4,
        "difficulty": "Medium",
        "image": "seed_22.png",
        "ingredients": [
            ("Chicken breast", "2"),
            ("Coconut milk", "400 ml"),
            ("Green curry paste", "3 tbsp"),
            ("Eggplant", "1"),
            ("Basil", "small bunch"),
            ("Rice", "250 g"),
            ("Lime", "1"),
            ("Fish sauce", "1 tbsp"),
        ],
        "steps": [
            "Fry the curry paste in a little coconut cream until fragrant.",
            "Add sliced chicken and cook 3 minutes.",
            "Pour in the coconut milk, add eggplant chunks and simmer 15 minutes.",
            "Season with fish sauce and lime, serve over rice with basil.",
        ],
    },
    {
        "name": "Mushroom Risotto",
        "category": "Dinner",
        "cook_time_minutes": 45,
        "servings": 4,
        "difficulty": "Hard",
        "image": "seed_23.png",
        "ingredients": [
            ("Arborio rice", "300 g"),
            ("Mushrooms", "400 g"),
            ("Onion", "1"),
            ("Garlic", "2 cloves"),
            ("Parmesan", "60 g"),
            ("Butter", "50 g"),
            ("Vegetable stock", "1.2 l"),
        ],
        "steps": [
            "Sauté the mushrooms in half the butter until golden, set aside.",
            "Soften chopped onion and garlic, add the rice and toast 2 minutes.",
            "Add hot stock a ladle at a time, stirring, about 18 minutes.",
            "Stir in mushrooms, parmesan and remaining butter; rest 2 minutes and serve.",
        ],
    },
    {
        "name": "Garlic Shrimp Pasta",
        "category": "Dinner",
        "cook_time_minutes": 25,
        "servings": 2,
        "difficulty": "Medium",
        "image": "seed_24.png",
        "ingredients": [
            ("Pasta", "250 g"),
            ("Shrimp", "300 g"),
            ("Garlic", "4 cloves"),
            ("Butter", "40 g"),
            ("Lemon", "1/2"),
            ("Parsley", "small bunch"),
            ("Chili flakes", "1 pinch"),
            ("Olive oil", "2 tbsp"),
        ],
        "steps": [
            "Cook the pasta; reserve a cup of pasta water.",
            "Sear the shrimp in oil 1 minute per side, add garlic, butter and chili flakes.",
            "Toss in the pasta with a splash of pasta water to make a glossy sauce.",
            "Finish with lemon juice and parsley.",
        ],
    },
    {
        "name": "Roast Chicken with Potatoes",
        "category": "Dinner",
        "cook_time_minutes": 90,
        "servings": 4,
        "difficulty": "Medium",
        "image": "seed_25.png",
        "ingredients": [
            ("Whole chicken", "1.5 kg"),
            ("Potato", "800 g"),
            ("Garlic", "1 head"),
            ("Lemon", "1"),
            ("Thyme", "5 sprigs"),
            ("Butter", "60 g"),
            ("Carrot", "2"),
        ],
        "steps": [
            "Rub the chicken with soft butter, salt and thyme; put lemon halves inside.",
            "Surround with potato chunks, carrots and garlic cloves.",
            "Roast at 190°C for about 75 minutes, basting twice.",
            "Rest 10 minutes before carving.",
        ],
    },
    # ---------------- Desserts ----------------
    {
        "name": "Chocolate Chip Cookies",
        "category": "Desserts",
        "cook_time_minutes": 30,
        "servings": 6,
        "difficulty": "Easy",
        "image": "seed_26.png",
        "ingredients": [
            ("Flour", "250 g"),
            ("Butter", "150 g"),
            ("Brown sugar", "120 g"),
            ("Sugar", "60 g"),
            ("Egg", "1"),
            ("Dark chocolate", "150 g"),
            ("Vanilla extract", "1 tsp"),
            ("Baking soda", "1/2 tsp"),
        ],
        "steps": [
            "Cream the butter with both sugars, then beat in the egg and vanilla.",
            "Fold in flour, baking soda and chopped chocolate.",
            "Scoop balls onto a tray and bake at 180°C for 11–12 minutes.",
            "Cool on the tray 5 minutes — they firm up as they cool.",
        ],
    },
    {
        "name": "Classic Cheesecake",
        "category": "Desserts",
        "cook_time_minutes": 90,
        "servings": 8,
        "difficulty": "Hard",
        "image": "seed_27.png",
        "ingredients": [
            ("Cream cheese", "600 g"),
            ("Sugar", "150 g"),
            ("Egg", "3"),
            ("Biscuits", "200 g"),
            ("Butter", "100 g"),
            ("Vanilla extract", "1 tsp"),
            ("Sour cream", "150 g"),
        ],
        "steps": [
            "Crush the biscuits, mix with melted butter and press into a springform base.",
            "Beat cream cheese with sugar, then eggs one at a time, then sour cream and vanilla.",
            "Pour over the base and bake at 160°C for about 55 minutes until just set.",
            "Cool completely, then chill at least 4 hours.",
        ],
    },
    {
        "name": "Chocolate Mug Cake",
        "category": "Desserts",
        "cook_time_minutes": 5,
        "servings": 1,
        "difficulty": "Easy",
        "image": "seed_28.png",
        "ingredients": [
            ("Flour", "4 tbsp"),
            ("Cocoa", "2 tbsp"),
            ("Sugar", "3 tbsp"),
            ("Milk", "4 tbsp"),
            ("Butter", "20 g"),
            ("Baking powder", "1/4 tsp"),
            ("Dark chocolate", "20 g"),
        ],
        "steps": [
            "Mix flour, cocoa, sugar and baking powder right in the mug.",
            "Stir in milk and melted butter until smooth, push chocolate into the middle.",
            "Microwave 70–90 seconds until risen but still fudgy in the center.",
        ],
    },
    {
        "name": "Apple Crumble",
        "category": "Desserts",
        "cook_time_minutes": 50,
        "servings": 6,
        "difficulty": "Easy",
        "image": "seed_29.png",
        "ingredients": [
            ("Apple", "5"),
            ("Flour", "150 g"),
            ("Butter", "100 g"),
            ("Sugar", "100 g"),
            ("Cinnamon", "1 tsp"),
            ("Oats", "50 g"),
            ("Lemon", "1/2"),
        ],
        "steps": [
            "Toss sliced apples with half the sugar, cinnamon and lemon juice; spread in a dish.",
            "Rub cold butter into flour, oats and remaining sugar until crumbly.",
            "Cover the apples with the crumble and bake at 180°C for 35 minutes until golden.",
        ],
    },
    {
        "name": "Tiramisu",
        "category": "Desserts",
        "cook_time_minutes": 30,
        "servings": 6,
        "difficulty": "Medium",
        "image": "seed_30.png",
        "ingredients": [
            ("Mascarpone", "400 g"),
            ("Egg", "3"),
            ("Sugar", "100 g"),
            ("Espresso", "250 ml"),
            ("Ladyfingers", "200 g"),
            ("Cocoa", "2 tbsp"),
        ],
        "steps": [
            "Whisk egg yolks with sugar until pale, fold in the mascarpone.",
            "Whip the whites to soft peaks and fold in gently.",
            "Dip ladyfingers briefly in cooled espresso and layer with the cream twice.",
            "Chill 4 hours and dust generously with cocoa.",
        ],
    },
]
